In [71]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: pandas in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (2.2.4)
Requirement already satisfied: matplotlib in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (2.2.4)
Requirement already satisfied: packaging>=20.0 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from seaborn) (2.2.4)
Requirement already satisfied: pandas>=1.2 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/sanketkakade/miniforge3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [72]:
file_path = '/Users/sanketkakade/Documents/DSBDA_TE/Assignment_01/data_titanic.csv'
df = pd.read_csv(file_path)

In [73]:
df.head()

,Pid,Survived,Pclass,Name,Sex,Age,SibSp,Parch,tkt,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S

In [74]:
df.tail()

,Pid,Survived,Pclass,Name,Sex,Age,SibSp,Parch,tkt,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7,NaN,Q

In [75]:
df.describe()

,Pid,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,31.785634
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.703730
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.000000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.000000
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.000000

In [76]:
df.dtypes

Pid           int64
Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
tkt          object
Fare          int64
Cabin        object
Embarked     object
dtype: object

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pid       891 non-null    int64
 1   Survived  891 non-null    int64
 2   Pclass    891 non-null    int64
 3   Name      891 non-null    object
 4   Sex       891 non-null    object
 5   Age       714 non-null    float64
 6   SibSp     891 non-null    int64
 7   Parch     891 non-null    int64
 8   tkt       891 non-null    object
 9   Fare      891 non-null    int64
 10  Cabin     204 non-null    object
 11  Embarked  889 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 83.7+ KB

In [78]:
df.columns

Index(['Pid', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'tkt', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [79]:
df = df.rename(
    columns={
        'Pid':'PassengerId',
        'tkt':'Ticket'
    }
)

In [80]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [81]:
df.shape

(891, 12)

In [82]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [83]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [84]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [85]:
df.isnull().sum().any()

np.True_

In [86]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [87]:
df[['Age','Fare']].value_counts()

Age   Fare
22.0  7       14
25.0  7       11
21.0  7       10
19.0  7        7
26.0  7        7
              ..
24.5  8        1
24.0  263      1
      247      1
      83       1
80.0  30       1
Name: count, Length: 512, dtype: int64

In [88]:
df.notnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,True,True,True,True,True,True,True,True,True,True,False,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,False,True
887,True,True,True,True,True,True,True,True,True,True,True,True
888,True,True,True,True,True,False,True,True,True,True,False,True
889,True,True,True,True,True,True,True,True,True,True,True,True
890,True,True,True,True,True,True,True,True,True,True,False,True

In [89]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare             int64
Cabin           object
Embarked        object
dtype: object

In [ ]:
# pandas.to_numeric(arg, errors='coerce')

In [90]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S

In [91]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S

In [92]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S

In [93]:
df['Fare'] = df['Fare'].astype(int)

In [94]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S

In [95]:
df.to_csv('data_titanic.csv',index=False)

In [96]:
import numpy as np

from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

standardised_data = scalar.fit_transform(df['Fare'].values.reshape(-1,1))
standardised_data.mean()

np.float64(3.787966324198065e-17)

In [97]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S

In [98]:
df['Fare'] = scalar.fit_transform(df['Fare'].values.reshape(-1,1))

In [99]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.498948,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.789405,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.498948,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.427056,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.478817,NaN,S

In [100]:
import numpy as np

def standard_scalar(data):
    mean = np.mean(data)
    std_dev = np.std(data)
    scaled_data = [(x-mean)/std_dev for x in data]
    return scaled_data

std_data = standard_scalar(df['Fare'])
np.mean(std_data)

np.float64(-3.987332972840069e-18)

In [101]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
normalised_data = scaler.fit_transform(df['Fare'].values.reshape(-1,1))
normalised_data
normalised_data.mean()

np.float64(0.062081316638608296)

In [102]:
df['Fare'] = scaler.fit_transform(df['Fare'].values.reshape(-1,1))
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.013672,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.138672,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.013672,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103516,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015625,NaN,S

In [103]:
import numpy as np
def minmaxscaler (data):
    min = np.min(data)
    max = np.max(data)
    nor_data = [(x-min)/(max-min) for x in data]
    return nor_data

scaler = minmaxscaler(df['Fare'])
print(np.mean(scaler))

0.062081316638608296

In [104]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Assuming your DataFrame is loaded as 'df'

# Apply Label Encoding to the 'Sex' column
label_encoder = LabelEncoder()
df['Sex_LabelEncoded'] = label_encoder.fit_transform(df['Sex'])

print("DataFrame with 'Sex' Label Encoded:")
print(df[['Sex', 'Sex_LabelEncoded']].head())

DataFrame with 'Sex' Label Encoded:
      Sex  Sex_LabelEncoded
0    male                 1
1  female                 0
2  female                 0
3  female                 0
4    male                 1

In [105]:
# do only when asked

import pandas as pd

# Assuming your DataFrame is loaded as 'df'

# Apply Dummy Coding to 'Sex' and 'Embarked'
# drop_first=True removes the first category column to avoid multicollinearity
df_dummies = pd.get_dummies(df[['Sex', 'Embarked']], drop_first=True)

print("DataFrame with Dummy Coded 'Sex' and 'Embarked':")
print(df_dummies.head())

# You can concatenate these new columns with your original DataFrame
df = pd.concat([df, df_dummies], axis=1)
print("\nOriginal DataFrame with Dummy Coded columns:")
print(df.head())

DataFrame with Dummy Coded 'Sex' and 'Embarked':
   Sex_male  Embarked_Q  Embarked_S
0      True       False        True
1     False       False       False
2     False       False        True
3     False       False        True
4      True       False        True

Original DataFrame with Dummy Coded columns:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket      Fare Cabin Embarked  Sex_LabelEncoded  \
0      0         A/5 21171  0.013672   NaN        S                 1
1      0          PC 17599  0.138672   C85        C                 0
2      0  STON/O2. 3101282  0.013672   NaN        S                 0
3      0            113803  0.103516  C123        S                 0
4      0            373450  0.015625   NaN        S                 1

   Sex_male  Embarked_Q  Embarked_S
0      True       False        True
1     False       False       False
2     False       False        True
3     False       False        True
4      True       False        True

In [106]:
#do if asked 

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Assuming your DataFrame is loaded as 'df'

# Handle missing values in 'Embarked' before One-Hot Encoding
df['Embarked'] = df['Embarked'].fillna('Unknown') # Replace NaN with a placeholder

# Apply One-Hot Encoding to 'Sex' and 'Embarked'
onehot_encoder = OneHotEncoder(sparse_output=False) # sparse_output=False returns a numpy array

# Fit and transform the selected columns
# Use .values.reshape(-1, 1) if encoding a single column
onehot_encoded_data = onehot_encoder.fit_transform(df[['Sex', 'Embarked']])

# Create a DataFrame from the one-hot encoded data
# Get the new column names
feature_names = onehot_encoder.get_feature_names_out(['Sex', 'Embarked'])
df_onehot = pd.DataFrame(onehot_encoded_data, columns=feature_names, index=df.index)

print("DataFrame with One-Hot Encoded 'Sex' and 'Embarked':")
print(df_onehot.head())

# You can concatenate these new columns with your original DataFrame
# df = pd.concat([df, df_onehot], axis=1)
# print("\nOriginal DataFrame with One-Hot Encoded columns:")
# print(df.head())

DataFrame with One-Hot Encoded 'Sex' and 'Embarked':
   Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  Embarked_Unknown
0         0.0       1.0         0.0         0.0         1.0               0.0
1         1.0       0.0         1.0         0.0         0.0               0.0
2         1.0       0.0         0.0         0.0         1.0               0.0
3         1.0       0.0         0.0         0.0         1.0               0.0
4         0.0       1.0         0.0         0.0         1.0               0.0